### PR TITLE
handling escape quote char

### PR DESCRIPTION
**Pull request by soymo**

### CODE REVIEW

**Comment by dbro** [comment]
Thanks for the pull request. Can you send an example of a csv file snippet that would need an escape character?

**Comment by soymo** [comment]
for example when you have json encoded value in csv:
field1,"{\"k1\": \"v1\",\"k2\": \"v2\"}"

**Comment by dbro** [comment]
Thanks. I'll think about how to include this in the next days. Interaction among nested or sequential encodings can be tricky.

**Comment by dbro** [comment]
Hi Grzegorz-
(Sorry to take so long to follow up)
Thanks for the suggestion, I can see how this might be useful in some cases. However, there are some other cases that are not well handled that I'd like to discuss with you before accepting the pull request.

The example you sent is inconsistent with the (admittedly not-quite-official) CSV standard as defined in https://tools.ietf.org/html/rfc4180 which makes no mention of escape characters. To appropriately include the double-quote character, it needs to be inside a quoted field and repeated. The data you sent should therefore be represented like this:
> field1,"{""k1"": ""v1"",""k2"": ""v2""}"
What did you use to generate the JSON, and can you adjust that source to use proper CSV formatting conventions?

Because there is no provision for an escape character in the standard, I'm concerned that the behavior is not well defined enough to include in csvquote. Here is an example data set that shows some unexpected behaviors that arise with the code as suggested:

> $ cat data-escapes.csv
> data1,data\,2,data3
> data4,data\
> 5,"data""6"
> data7,"data\,8","data9"
> data10,"data\
> 11","data\"12"
>
> $ csvquote -e '\' data-escapes.csv | wc -l
> 6  <-- should be 4
>
> $ ./csvquote -e '\' testdata-escapes.csv | awk 'BEGIN {FS = ","} (1) {print NF}'
> 4 <-- should be 3
> 2 <-- should be 3
> 2 <-- should not be here
> 4 <-- should be 3
> 2 <-- should be 3
> 2 <-- should not be here

Please feel free to resubmit another pull request that correctly handles these (and possibly other) test cases involving escape characters. Thanks again
Dan

**Pull request closed without merging**
