### PR TITLE
Attempt to optimize

### PR DESCRIPTION
**Pull request by jarnos**
Use FS="", i.e. $i = i'th character (or byte) in line in order to optimize and simplify code. Take more advance of quoteposition variable. Speed may vary according to awk implementation used.

### CODE REVIEW

**Comment by dbro** [comment]
Hi jarnos- Thanks for the suggestion. However, I will reject this pull request for the following reasons:

* The awk port of csvquote is not worth updating, as it is only a limited test that does not support any command line parameters. The "other-languages" branch is an unmaintained branch that I use for learning new programming languages. For people who want high performance, the primary C implementation is much faster than the awk(2.5 seconds to process the same file as above).

* This change does not improve performance. I ran it on a ~4 million row, 500MB csv file and it took 103 seconds. The existing version took 83 seconds.

Dan

**Comment by jarnos** [comment]
Hi dbro. You can use command line options the way I have shown in the first example included in comments in the code (line 6 and 7).

I disagree about the performance. Performance depends on the awk implementation used, and on the input file. Let me be more specific.

Suppose you have csvquote.awk and csvquote-js.awk in the current directory. The former one is the current script in your repository. The latter one is the modified script. The following BASH script creates files called a.csv and b.csv in the current directory and runs the scripts using them by mawk and gawk and shows the execution times.
```bash
#!/bin/bash

test() {
set -x
time mawk -f ./csvquote.awk "$1" >/dev/null
time mawk -f ./csvquote-js.awk "$1" >/dev/null
time gawk -f ./csvquote.awk "$1" >/dev/null
time gawk -f ./csvquote-js.awk "$1" >/dev/null
time gawk -b -f ./csvquote.awk "$1" >/dev/null
time gawk -b -f ./csvquote-js.awk "$1" >/dev/null
set +x
}

printf "%0.s\"1,\"," $(seq 10000) >a.csv
test a.csv
>b.csv
for ((i=0;i<1000;i++)); do printf "%0.s1," $(seq 10000) >>b.csv; printf "\"2\"\n" >>b.csv; done
test b.csv
```
In my system the modified script is significantly faster, except for a.csv, if run by mawk, when it is significantly slower.

**Comment by dbro** [comment]
Hi jarnos-
Sorry, I don't think I was clear in my description.

The command line parameters I was referring to are the ones that the regular C implementation of csvquote supports as defined in the getopt part of the code, usd:tq:r: The awk version is only an experimental version, and it is not intended to be installed or used because it's so much slower and doesn't support these command line parameters.

I'll repeat what I said before: speeding up the csvquote awk version is not an important improvement to the code. The speed of the awk script will never be within an order of magnitude of the C version.
Dan

**Comment by jarnos** [comment]
Oh, yes I understand that the syntax for the options is different with the awk script as such. I also don't suggest the awk script should be used instead of the binary for the purpose, but my point is that even the awk script can be optimized significantly, and the implementation of awk virtual machine also has great significance. That also may affect to the relative speed comparison you have in README.md. Though my test files have about 10000 fields on each record, which is much more than in most cases in practice, I suppose.  Which implementation of awk did you use in your testing and which kind of file?

**Comment by dbro** [comment]
Hi Jarnos- mawk is what's enabled on my distribution.

The number of fields per row is not the main factor for speed, it's the total number of bytes in the file. csvquote should be ready to work with a few hundred MB of data without slowing down a typical cut/sort/uniq pipeline down too much (<2x)

**Pull request closed without merging**
